---
apiVersion: v1
kind: Pod
metadata:
  name: my-vault
spec:
  containers:
  - name: vault
    image: vault
    ports:
    - containerPort: 8200
      protocol: TCP
    env:
    - name: VAULT_DEV_ROOT_TOKEN_ID
      value: "SeCrEt"
    - name: VAULT_DEV_LISTEN_ADDRESS
      value: "0.0.0.0:8200"
    - name: VAULT_ADDR
      value: "http://127.0.0.1:8200"
    - name: VAULT_TOKEN
      value: "SeCrEt"