---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: nginx
    env:
      - name: NGINX_SERVER_NAME
        valueFrom:
          configMapKeyRef:
            name: domain
            key: name       
    volumeMounts:
      - name: config
        mountPath: /etc/nginx
        readOnly: true
  volumes:
  - name: config
    configMap: 
      name: nginx-config