apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  nginx.conf: |
    user  nginx;
    worker_processes  5;
    pid /var/run/nginx.pid;
    events {
      worker_connections  10240;
    }
    http {
      error_log   /var/log/nginx/error.log;
      access_log  /var/log/nginx/access.log;
      server {
          listen      80;
          server_name netology.ru;
          location / {
              root    html;  
              index   index.html index.htm;
          }
      }
    } 