apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: nginx
    volumeMounts:
    - name: mysecret
      mountPath: "/etc/secret"
      readOnly: true
  volumes:
  - name: mysecret
    secret:
      secretName: domain-cert