{
 "title": "My dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 9, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1) / count(count(node_cpu_seconds_total) by (cpu)) * 100",
     "legendFormat": "1m"
    },
    {
     "expr": "avg(node_load5) / count(count(node_cpu_seconds_total) by (cpu)) * 100",
     "legendFormat": "5m"
    },
    {
     "expr": "avg(node_load15) / count(count(node_cpu_seconds_total) by (cpu)) * 100",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Free RAM",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemFree_bytes" }
   ]
  },
  {
   "title": "Disk usage",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype!=\"tmpfs\"}",
     "legendFormat": "free"
    },
    {
     "expr": "node_filesystem_size_bytes{fstype!=\"tmpfs\"}-node_filesystem_avail_bytes{fstype!=\"tmpfs\"}",
     "legendFormat": "used"
    }
   ]
  }
 ]
}