---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
  labels:
    app: back
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: backend
        image: {{ .Values.image.backrepo }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        ports:
        - containerPort: {{ .Values.bPort }}
        env:
          - name: DATABASE_URL
            value: postgres://postgres:postgres@db:{{ .Values.dbPort }}/news